### PR TITLE
Add API controllers, routes, and a txt file with documentation

### PR DESCRIPTION
**Pull request by EmiLoKiJu**
Added controlers and routes for:
users: create
parachutes: create, index, show, delete
reservations: create, index, show, delete

Implemented login using API with token system, using the jwt gem. Here's how you use Postman to autologin when doing API requests to other routes than login:

image

More info in the API_doc.txt.

In javascript, the call to login using axios looks like this:

```
const response = await axios.post('http://localhost:3000/login', {
  username: user
}, {
  headers: {
    'Content-Type': 'application/json',
  },
});
```

The call to any site with the Authorize header using axios looks like this:

```
export const getGreetings = createAsyncThunk('greetings/getGreetings', async (token) => {
  console.log(token);
  const response = await axios.get(
    'http://localhost:3000/greetings/random',
    { headers: {
        'Authorization': `bearer ${token}`
      }
    }
  );
  return response.data.greeting;
});
```

### CODE REVIEW

**Review by Ali-0111 — APPROVED** [review]
Hi @EmiLoKiJu 🙋‍♀️,
Excellent work! 💯
You have done a great job processing API for the project 🎊 🥳
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit:
Congratulations!!!🎊 🥳

Highlights 🌞
✔️ Well-commits message
✔️ Well-documented
✔️ All required tables created as expected

Status: Approved ✔️


Cheers 🥂 and Happy coding!!! 👯
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @Ali-0111 in your question so I can receive the notification.

**Comment by Ali-0111** [comment]
@EmiLoKiJu 
Before merging, please update this part:
image

**Comment by Ali-0111** [comment]
@EmiLoKiJu ,
Please add data inside `seed.rb`. so, whenever we want to clone . we need to create the database and there should be some data for demo. right now, I hardly could add some data to database.

**Comment by EmiLoKiJu** [comment]
> @EmiLoKiJu Before merging, please update this part: image

That was just an example of how to make a call from the frontend with axios. That part would have to be updated from the other repository.

**Comment by EmiLoKiJu** [comment]
> @EmiLoKiJu , Please add data inside `seed.rb`. so, whenever we want to clone . we need to create the database and there should be some data for demo. right now, I hardly could add some data to database.

I will ;)

If you added data to the database that means you tested it, and I wanted that :D

**Pull request merged**
